version: '3.8'
services:
    jave-maven-app:
      image: ${IMAGE}
      ports:
      - 8080:8080
    postgres:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=my-pwd 

    